#!/bin/sh

##
# font-file-info-best-dirname:
# given a font file, output the best dirname.
#
# Syntax:
#
#     font-file-info-best-dirname <font-file>
#
# Example:
#
#     $ font-file-info-best-dirname ALPHA_BRAVO_BI.OTF
#     Alpha-Bravo
#
# The best dirname syntax is:
#
#     <best-family>
#
# ## Path format
#
# The path part format is:
#
#    * Preserve alphanumeric characters.
#
#    * Convert all other characters to hyphens.
#
#    * Merge successive hyphens.
#
#    * Delete leading/trailing hyphens.
#
#
# ## Tracking
#
# * Command: font-file-info-best-dirname
# * Version: 3.0.0
# * Created: 2015-12-19
# * Updated: 2023-05-18T11:38:47Z
# * License: GPL-2.0 or GPL-3.0 or contact us for more
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
file="$1"

safe_path_part(){
    printf '%s' "$1" | sed 's/[^[:alnum:]]/-/g; s/---*/-/g; s/^-//; s/-$//;'
}

best_family=$(font-file-info-best-family "$file")
printf '%s' $(safe_path_part "$best_family")
