#!/bin/sh

##
# font-file-info-best-path:
# given a font file, output the best path.
#
# Syntax:
#
#     font-file-info-best-path <font-file>
#
# Example:
#
#   $ font-file-to-path ALPHA_BRAVO_BI.OTF
#   Alpha-Bravo/Alpha-Bravo-Bold-Italic.otf
#
# The best path syntax is:
#
#     <best-family>/<best-name>.<best-extension>
#
# ## Path piece format
#
# The path piece format is:
#
#    * Preserve alphanumeric characters.
#
#    * Convert all other characters to hyphens.
#
#    * Merge successive hyphens.
#
#    * Delete leading/trailing hyphens.
#
#
# ## Tracking
#
# * Command: font-file-info-best-path
# * Version: 3.0.0
# * Created: 2015-12-19
# * Updated: 2023-05-18T11:38:47Z
# * License: GPL-2.0 or GPL-3.0 or contact us for more
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
file="$1"

safe_path_part(){
    printf '%s' "$1" | sed 's/[^[:alnum:]]/-/g; s/---*/-/g; s/^-//; s/-$//;'
}

best_family=$(font-file-info-best-family "$file")
best_name=$(font-file-info-best-name "$file")
best_extension=$(font-file-info-best-extension "$file")
printf '%s/%s.%s' $(safe_path_part "$best_family") $(safe_path_part "$best_name") $(safe_path_part "$best_extension")
