#!/bin/sh

##
# font-file-info-family:
# given a font file, output the family name.
#
# Syntax:
#
#     font-file-info-family <font-file>
#
# Example:
#
#     $ font-file-info-family ALPHA-BRAVO-BI.OTF
#     Alpha Bravo
#
# ## Implementation
#
# This script is implemented on OS X by using `otfinfo`.
# To get this, use `brew install lcdf-typetools`.
#
# To Do:
#
#   * Implement on Linux and Windows
#
#   * Get other font fields
#
# ## Tracking
#
# * Command: font-file-info-family 
# * Version: 2.0.0
# * Created: 2015-12-19
# * Updated: 2020-03-25
# * License: GPL
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
file="$1"
otfinfo --info "$file"| sed -n 's/^Preferred family: */1/p; s/^Family: */2/p' | sort -u | head -1 | sed 's/^.//'
