#!/bin/sh

##
# font-file-info-full-name:
# given a font file, output the full name.
#
# Syntax:
#
#     font-file-info-full-name <font-file>
#
# Example:
#
#     $ font-file-info-full-name ALPHA-BRAVO-BI.OTF
#     Alpha Bravo Bold Italic
#
# ## Implementation
#
# This script is implemented on OS X by using `otfinfo`.
# To get this, use `brew install lcdf-typetools`.
#
# To Do:
#
#   * Implement on Linux and Windows
#
#   * Get other font fields
#
# ## Tracking
#
# * Command: font-file-info-full-name
# * Version: 2.0.0
# * Created: 2015-12-19
# * Updated: 2020-03-25
# * License: GPL
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
file="$1"
otfinfo --info "$file" | sed -n 's/Full name: *//p'
