#!/bin/sh

##
# font-file-info-best-basename:
# given a font file, output the best basename.
#
# Syntax:
#
#     font-file-info-best-basename <font-file>
#
# Example:
#
#     $ font-file-info-best-basename ALPHA_BRAVO_BI.OTF
#     Alpha-Bravo-Bold-Italic.otf
#
# The best basename syntax is:
#
#     <best-name>.<best-extension>
#
# ## Path format
#
# The path part format is:
#
#    * Preserve alphanumeric characters.
#
#    * Convert all other characters to hyphens.
#
#    * Merge successive hyphens.
#
#    * Delete leading/trailing hyphens.
#
#
# ## Tracking
#
# * Command: font-file-info-best-basename
# * Version: 3.0.0
# * Created: 2015-12-19
# * Updated: 2023-05-18T11:38:47Z
# * License: GPL-2.0 or GPL-3.0 or contact us for more
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
file="$1"

safe_path_part(){
    printf '%s' "$1" | sed 's/[^[:alnum:]]/-/g; s/---*/-/g; s/^-//; s/-$//;'
}

best_name=$(font-file-info-best-name "$file")
best_extension=$(font-file-info-best-extension "$file")
printf '%s.%s' $(safe_path_part "$best_name") $(safe_path_part "$best_extension")
